import Head from "next/head";
import React from "react";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
export default function about() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={`main`}> 
      <h1>About Page</h1>
        <div className={`description`}>
          <a href="/" target="_blank" rel="noopener noreferrer">
            Ir a Home
          </a>
          <p>
            Get started by editing&nbsp;
            <code className={`code`}>pages/about.tsx</code>
          </p>
          <div></div>
        </div>
      </main>
    </>
  );
}
