import Head from "next/head";
import styles from "./MainLayout.module.css";
import Navbar from "../Navbar";
import { Inter } from "next/font/google";
import { FC } from "react";
import { PageProps } from "@/interfaces/global.interface";
const inter = Inter({ subsets: ["latin"] });

export const MainLayout: FC<PageProps> = ({children}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`${styles.main} ${inter.className}`}>{children}</main>
    </>
  );
};
